---
- name: Prerequisites
  hosts: all
  remote_user: root
  roles:
    - pre_reqs

- name: DNS
  hosts: oselab
  remote_user: root
  roles:
    - dns

- name: NFS
  hosts: nfs
  remote_user: root
  roles:
    - nfs

- name: docker
  hosts: ose
  remote_user: root
  roles:
    - docker

