---
- name: Prerequisites
  hosts: all
  remote_user: root
  roles:
    - { role: pre_reqs, tags: 'pre_reqs' }

- name: DNS
  hosts: oselab
  remote_user: root
  roles:
    - { role: dns, tags: 'dns' }

- name: NFS
  hosts: nfs
  remote_user: root
  roles:
    - { role: nfs, tags: 'nfs' }

- name: docker
  hosts: ose
  remote_user: root
  roles:
    - { role: docker, tags: 'docker' }

