---
  - name: Install base packages. 
    sudo: yes
    yum: name={{ items }}  state=present 
    when:  variable is defined
    with_items:
      - wget 
      - git
      - net-tools
      - bind-utils
      - iptables-services 
      - bridge-utils
      - bash-completion
      - screen

  - name: Update all packages.
    sudo: yes
    yum: name=*  state=latest
