---
  - name: Install base packages.
    become: yes
    yum:
      name: "{{ items }}"
      state: latest
    when:  variable is defined
    with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - screen

  - name: Update all packages.
    become: yes
    yum: name=*  state=latest
