---
  - name: rhn | Check subscription status
    command: "/usr/bin/subscription-manager status"
    ignore_errors: yes
    changed_when: no
    register: is_registered

  - name: rhn | register to rhn
    command: "/usr/bin/subscription-manager register --username={{ rhn_user }} --password={{ rhn_password }}"
    when: is_registered.rc != 0
    serial: "50%"
    tags:
      - rhn

  - name: rhn | Auto-attach to RHN Pool.
    command: "/usr/bin/subscription-manager attach --auto"
    when: is_registered.rc != 0
    serial: "50%"
    tags:
      - rhn

  - name: rhn | configure red hat repos
    command: "/usr/bin/subscription-manager repos --disable * --enable rhel-7-server-rpms --enable rhel-7-server-ose-3.1-rpms --enable rhel-7-server-extras-rpms"
    when: is_registered.rc != 0
    tags:
      - rhn
