---
# handlers file for ose-bootcamp
  - name: enable nfs
    sudo: yes
    service:
      enabled: yes
      name: nfs-server
    notify: enable rpcbind

  - name: enable rpcbind
    sudo: yes
    service:
      enabled: yes
      name: rpcbind

  - name: restart rpcbind
    sudo: yes
    service:
      name: rpcbind
      state: restarted

  - name: restart nfs-server
    sudo: yes
    service:
      name: nfs-server
      state: restarted
    notify: restart rpcbind

  - name: reload firewalld
    sudo: yes
    shell: "firewall-cmd --reload"
    ignore_errors: yes

