---
  - name: enable named
    service:
      name: named
      enabled: yes

  - name: restart named
    service:
      name: named
      state: restarted

  - name: reload firewalld
    sudo: yes
    shell: "/usr/bin/firewall-cmd --reload"
    ignore_errors: yes
