---
  - name: create export directory
    file:
      path: /opt/nfs/registry
      state: directory
      recurse: yes
      owner: nfsnobody
      group: nfsnobody
      mode: 0755

  - name: adding export to nfs
    lineinfile:
      dest: /etc/exports
      state: present
      line: "/opt/nfs/registry  *(root_squash,rw,sync)"
    notify: 
      - restart rpcbind
      - restart nfs-server
