---
  - name: install nfs and rpcbind
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - nfs-utils
      - rpcbind
    notify: 
      - enable rpcbind
      - enable nfs-server
    tags:
      - nfs

  - name: open nfs port on firewalld
    firewalld:
      permanent: "{{ item.permanent }}"
      service: "{{ item.service | default(omit) }}"
      state: "{{ item.state }}"
      zone: "{{ item.zone }}"
      port: "{{ item.port | default(omit) }}"
    with_items: firewalld_rules
    notify: reload firewalld
    tags:
      - nfs
