---
# vars file for ose-bootcamp
firewalld_rules:
  - permanent: yes
    service: nfs
    state: enabled
    zone: public

  - permanent: yes
    port: 111/udp
    state: enabled
    zone: public

  - permanent: yes
    port: 111/tcp
    state: enabled
    zone: public

  - permanent: yes
    service: mountd
    state: enabled
    zone: public
