---
  - name: Capture guid
    shell: "hostname|cut -f2 -d-|cut -f1 -d."
    register: guid

  - name: Set guid paramater
    set_fact:
      guid: "{{ guid.stdout }}"

  - debug:
      msg: "GUID for environment is {{ guid }}"

  - name: Install bind rpms
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - bind
      - bind-utils
    notify: enable named

  - name: Set infra0 paramater
    set_fact:
      infra0: "{{ hostvars['infranode00-' + guid + '.oslab.opentlc.com']['ansible_default_ipv4.address'] }}"

  - name: set infra1 paramater
    set_fact:
      infra1: "{{ hostvars['infranode01-' + guid + '.oslab.opentlc.com']['ansible_default_ipv4.address'] }}"

  - name: set domain paramater
    set_fact:
      domain: "cloudapps-{{ guid }}.oslab.opentlc.com"

  - debug:
      msg: "Domain for environment is {{ domain }}"

  - name: Create zone directory
    file:
      state: directory
      path: /var/named/zones/
      owner: named
      group: named

  - name: Configure zone file
    template:
      src: domain.db.j2
      dest: /var/named/zones/{{ domain }}.db
      owner: named
      group: named

  - name: Restore SELinux context on zone file and dir
    shell: "restorecon -Rv /var/named/zones/"

  - name: Configure named.conf
    template:
      src: named.conf.j2
      dest: /etc/named.conf
      owner: root
      group: named

  - name: open port for DNS on firewalld
    sudo: yes
    firewalld:
      permanent: yes
      service: dns
      state: enabled
      zone: public

#TODO: add idempotence here
  - name: Restore SELinux context on named.conf
    shell: "restorecon -Rv /etc/named.conf"
    notify: restart named
