---
  - name: Capture guid for OpenTLC
    shell: "hostname|cut -f2 -d-|cut -f1 -d."
    register: guid

  - name: Set guid paramater for OpenTLC
    set_fact:
      guid: "{{ guid.stdout }}"

  - name: Install bind rpms
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - bind
      - bind-utils
    notify: enable named

  - name: Get infra00 external IP
    shell: "host infranode00-{{ guid }}.oslab.opentlc.com  ipa.opentlc.com |grep infranode | awk '{print $4}'"
    register: infranode00ip

  - name: Set infra0 paramater
    set_fact:
      infra0: "{{ infranode00ip.stdout }}"

  - name: Get infra01 external IP
    shell: "host infranode00-{{ guid }}.oslab.opentlc.com  ipa.opentlc.com |grep infranode | awk '{print $4}'"
    register: infranode01ip

  - name: set infra1 paramater
    set_fact:
      infra1: "{{ infranode01ip.stdout }}"

  - name: set domain paramater
    set_fact:
      domain: "cloudapps-{{ guid }}.oslab.opentlc.com"

  - name: Create zone directory
    file:
      state: directory
      path: /var/named/zones/
      owner: named
      group: named

  - name: Configure zone file
    template:
      src: domain.db.j2
      dest: /var/named/zones/{{ domain }}.db
      owner: named
      group: named

#TODO: add idempotence here
  - name: Restore SELinux context on zone file and directory
    shell: "restorecon -Rv /var/named/zones/"

  - name: Configure named.conf
    template:
      src: named.conf.j2
      dest: /etc/named.conf
      owner: root
      group: named

  - name: open ports for DNS on firewalld
    sudo: yes
    firewalld:
      permanent: yes
      service: dns
      state: enabled
      zone: public
    notify: reload firewalld

#TODO: add idempotence here
  - name: Restore SELinux context on named.conf
    shell: "restorecon -Rv /etc/named.conf"
    notify: restart named
